# Introduction to `numpy` library

In [26]:
import os
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'newsmallgray.png',
 'numpy_intro.ipynb',
 'smallgray.png']

In [4]:
import numpy as np
n = np.arange(30)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [7]:
n.shape

(30,)

In [8]:
n.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
n.reshape(5,6).T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [11]:
n.reshape(3, 5, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [15]:
print(n.reshape(3,5,2).T)

[[[ 0 10 20]
  [ 2 12 22]
  [ 4 14 24]
  [ 6 16 26]
  [ 8 18 28]]

 [[ 1 11 21]
  [ 3 13 23]
  [ 5 15 25]
  [ 7 17 27]
  [ 9 19 29]]]


In [17]:
type(n)

numpy.ndarray

In [19]:
m = np.asarray([[2,3],[3,5], [5,8]])
m

array([[2, 3],
       [3, 5],
       [5, 8]])

# Intro to OpenCV:

In [22]:
import cv2
# if grayscale read pass 0 or if bgr read pass 1
im_g = cv2.imread('smallgray.png', 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
type(im_g)

numpy.ndarray

In [24]:
im_c = cv2.imread('smallgray.png', 1) # read as bgr image
im_c

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [25]:
cv2.imwrite('newsmallgray.png', im_g)

True

# slicing numpy array's

In [27]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [29]:
im_g[0:,:3]

array([[187, 158, 104],
       [198, 125, 255],
       [209, 134, 255]], dtype=uint8)

In [30]:
im_gt = im_g[0:,:3].T
im_gt

array([[187, 198, 209],
       [158, 125, 134],
       [104, 255, 255]], dtype=uint8)

# Traversing through numpy array:

In [35]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [37]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [38]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


# numpy array stacking:

In [44]:
im_h = np.hstack((im_g, im_gt))
im_h

array([[187, 158, 104, 121, 143, 187, 198, 209],
       [198, 125, 255, 255, 147, 158, 125, 134],
       [209, 134, 255,  97, 182, 104, 255, 255]], dtype=uint8)

In [46]:
# im_v = np.vstack((im_g, im_gt)) won't work as shape doesn't match
im_v = np.vstack((im_g.T, im_gt))
im_v

array([[187, 198, 209],
       [158, 125, 134],
       [104, 255, 255],
       [121, 255,  97],
       [143, 147, 182],
       [187, 198, 209],
       [158, 125, 134],
       [104, 255, 255]], dtype=uint8)

In [51]:
im_v3 = np.vstack((im_gt,im_g.T,im_gt))
im_v3

array([[187, 198, 209],
       [158, 125, 134],
       [104, 255, 255],
       [187, 198, 209],
       [158, 125, 134],
       [104, 255, 255],
       [121, 255,  97],
       [143, 147, 182],
       [187, 198, 209],
       [158, 125, 134],
       [104, 255, 255]], dtype=uint8)

In [48]:
cv2.imwrite('anothergrayim_v.png', im_v)

True

In [49]:
cv2.imwrite('anothergrayim_h.png', im_h)

True

In [52]:
cv2.imwrite('anothergrayim_v3.png', im_v3)

True

# spliting numpy array:

In [69]:
im_v.shape

(8, 3)

In [54]:
lst = np.hsplit(im_v, 3)
lst

[array([[187],
        [158],
        [104],
        [121],
        [143],
        [187],
        [158],
        [104]], dtype=uint8),
 array([[198],
        [125],
        [255],
        [255],
        [147],
        [198],
        [125],
        [255]], dtype=uint8),
 array([[209],
        [134],
        [255],
        [ 97],
        [182],
        [209],
        [134],
        [255]], dtype=uint8)]

In [71]:
lst_h = np.hsplit(im_h, 4)
lst_h

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8),
 array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8),
 array([[143, 187],
        [147, 158],
        [182, 104]], dtype=uint8),
 array([[198, 209],
        [125, 134],
        [255, 255]], dtype=uint8)]

In [75]:
lst_v = np.vsplit(im_h, 3)
lst_v

[array([[187, 158, 104, 121, 143, 187, 198, 209]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 158, 125, 134]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 104, 255, 255]], dtype=uint8)]